dist: trusty

language: go

go:
  - 1.9

before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/mattn/goveralls

install:
  - make deps

script:
  - travis_wait 20 goveralls -service=travis-ci
