apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-standby-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "17"
  # Make this a standby cluster. You can specify s3_wal_path or gs_wal_path for WAL archive,
  # standby_host for remote primary streaming, or combine standby_host with either WAL path.
  # Note: s3_wal_path and gs_wal_path are mutually exclusive.
  standby:
    # s3_wal_path: "s3://mybucket/spilo/acid-minimal-cluster/abcd1234-2a4b-4b2a-8c9c-c1234defg567/wal/14/"
    standby_host: "acid-minimal-cluster.default"
    # standby_port: "5432"
