apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-standby-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "14"
  # Make this a standby cluster and provide either the s3 bucket path of source cluster or the remote primary host for continuous streaming.
  standby:
    s3_wal_path: "s3://path/to/bucket/containing/wal/of/source/cluster/"
    # standby_host: ""
    # standby_port: ""