apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator-ui.name" . }}
    helm.sh/chart: {{ template "postgres-operator-ui.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ template "postgres-operator-ui.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "postgres-operator-ui.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "postgres-operator-ui.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        team: "acid" # Parameterize?
    spec:
      serviceAccountName: {{ include "postgres-operator-ui.serviceAccountName" . }}
      containers:
        - name: "service"
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: "/health"
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "APP_URL"
              value: "http://localhost:8081"
            - name: "OPERATOR_API_URL"
              value: {{ .Values.envs.operatorApiUrl }}
            - name: "OPERATOR_CLUSTER_NAME_LABEL"
              value: {{ .Values.envs.operatorClusterNameLabel }}
            - name: "RESOURCES_VISIBLE"
              value: "{{ .Values.envs.resourcesVisible }}"
            - name: "TARGET_NAMESPACE"
              value: "{{ .Values.envs.targetNamespace }}"
            - name: "TEAMS"
              value: |-
                [
                  "acid"
                ]
            - name: "OPERATOR_UI_CONFIG"
              value: |-
                {
                  "docs_link":"https://postgres-operator.readthedocs.io/en/latest/",
                  "dns_format_string": "{1}-{0}.{2}",
                  "databases_visible": true,
                  "master_load_balancer_visible": true,
                  "nat_gateways_visible": false,
                  "replica_load_balancer_visible": true,
                  "resources_visible": true,
                  "users_visible": true,
                  "postgresql_versions": [
                    "12",
                    "11",
                    "10",
                    "9.6",
                    "9.5"
                  ]
                }
