apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresteams.acid.zalan.do
  labels:
    app.kubernetes.io/name: postgres-operator
spec:
  group: acid.zalan.do
  names:
    kind: PostgresTeam
    listKind: PostgresTeamList
    plural: postgresteams
    singular: postgresteam
    shortNames:
    - pgteam
    categories:
    - all
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
          - kind
          - apiVersion
          - spec
        properties:
          kind:
            type: string
            enum:
              - PostgresTeam
          apiVersion:
            type: string
            enum:
              - acid.zalan.do/v1
          spec:
            type: object
            properties:
              additionalSuperuserTeams:
                type: object
                description: "Map for teamId and associated additional superuser teams"
                additionalProperties:
                  type: array
                  nullable: true
                  description: "List of teams to become Postgres superusers"
                  items:
                    type: string
              additionalTeams:
                type: object
                description: "Map for teamId and associated additional teams"
                additionalProperties:
                  type: array
                  nullable: true
                  description: "List of teams whose members will also be added to the Postgres cluster"
                  items:
                    type: string
              additionalMembers:
                type: object
                description: "Map for teamId and associated additional users"
                additionalProperties:
                  type: array
                  nullable: true
                  description: "List of users who will also be added to the Postgres cluster"
                  items:
                    type: string
