apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: postgresqls.acid.zalan.do
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: acid.zalan.do
  names:
    kind: postgresql
    listKind: postgresqlList
    plural: postgresqls
    singular: postgresql
    shortNames:
    - pg
  additionalPrinterColumns:
  - name: Team
    type: string
    description: Team responsible for Postgres CLuster
    JSONPath: .spec.teamId
  - name: Version
    type: string
    description: PostgreSQL version
    JSONPath: .spec.postgresql.version
  - name: Pods
    type: integer
    description: Number of Pods per Postgres cluster
    JSONPath: .spec.numberOfInstances
  - name: Volume
    type: string
    description: Size of the bound volume
    JSONPath: .spec.volume.size
  - name: CPU-Request
    type: string
    description: Requested CPU for Postgres containers
    JSONPath: .spec.resources.requests.cpu
  - name: Memory-Request
    type: string
    description: Requested memory for Postgres containers
    JSONPath: .spec.resources.requests.memory
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Status
    type: string
    description: Current sync status of postgresql resource
    JSONPath: .status.PostgresClusterStatus
  scope: Namespaced
  subresources:
    status: {}
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operatorconfigurations.acid.zalan.do
  labels:
    app.kubernetes.io/name: {{ template "postgres-operator.name" . }}
    helm.sh/chart: {{ template "postgres-operator.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: acid.zalan.do
  names:
    kind: OperatorConfiguration
    listKind: OperatorConfigurationList
    plural: operatorconfigurations
    singular: operatorconfiguration
    shortNames:
    - opconfig
  additionalPrinterColumns:
  - name: Image
    type: string
    description: Spilo image to be used for Pods
    JSONPath: .configuration.docker_image
  - name: Cluster-Label
    type: string
    description: Label for K8s resources created by operator
    JSONPath: .configuration.kubernetes.cluster_name_label
  - name: Service-Account
    type: string
    description: Name of service account to be used
    JSONPath: .configuration.kubernetes.pod_service_account_name
  - name: Min-Instances
    type: integer
    description: Minimum number of instances per Postgres cluster
    JSONPath: .configuration.min_instances
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  subresources:
    status: {}
  version: v1
